### ISSUE TITLE
使用RecyclerView 的Item当点击View 第一次显示，X轴偏移量失效，二次正常

### ISSUE THREAD

**Issue by edifangyi** [jzyhywxz/PopupWindow#1]

**Comment by edifangyi** [comment]
找到原因了
           public int[] getOffset(View anchor, PopupWindow window)  
方法中，
            View view = window.getContentView();
没有绘制，
           view.getWidth() = 0
所以直接贴边

我临时的解决方法是
https://blog.csdn.net/dragonldg/article/details/52934242
这个样子

**Comment by jzyhywxz** [comment]
@edifangyi 谢谢！您说的这个问题我一开始没有考虑到，您的解决方案是可以一试的。如果可以的话，希望您能够使用pull request来修复这个bug！万分感谢！
